"""Extract the Garmin Connect activity glyphs used by Motion Black.

The input is Garmin's SVG icon font. The repository owner has permission to use
these icons. Run this script only when refreshing the checked-in icon module and
documentation assets from an authorized copy of that font.
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path
import xml.etree.ElementTree as ET


GLYPHS = (
    "activities",
    "activity-climbing",
    "activity-cycling",
    "activity-elliptical",
    "activity-fitness-equipment",
    "activity-golf",
    "activity-hiking",
    "activity-marine",
    "activity-motorcycle",
    "activity-multisport-people",
    "activity-multisport",
    "activity-other",
    "activity-running",
    "activity-swimming",
    "activity-uncategorized",
    "activity-walking",
)

SVG_NS = "http://www.w3.org/2000/svg"
VIEW_BOX = "0 0 320 320"
PATH_TRANSFORM = "translate(0 256) scale(1 -1)"


def extract_paths(source: Path) -> dict[str, str]:
    root = ET.parse(source).getroot()
    found = {
        glyph.attrib["path-name"]: glyph.attrib["d"].strip()
        for glyph in root.iter(f"{{{SVG_NS}}}glyph")
        if glyph.attrib.get("path-name") in GLYPHS
    }
    missing = sorted(set(GLYPHS) - set(found))
    if missing:
        raise ValueError(f"Missing Garmin glyphs: {', '.join(missing)}")
    return {name: found[name] for name in GLYPHS}


def write_module(target: Path, paths: dict[str, str]) -> None:
    serialized = json.dumps(paths, ensure_ascii=False, indent=2)
    target.write_text(
        "// Generated by scripts/extract_garmin_activity_icons.py from an authorized\n"
        "// Garmin Connect SVG font copy. Do not edit path data by hand.\n"
        "import { createElement, forwardRef } from \"react\";\n\n"
        f"export const GARMIN_ACTIVITY_PATHS = Object.freeze({serialized});\n\n"
        f"export const GARMIN_ICON_VIEW_BOX = \"{VIEW_BOX}\";\n"
        f"export const GARMIN_ICON_TRANSFORM = \"{PATH_TRANSFORM}\";\n\n"
        "const iconComponents = new Map();\n\n"
        "export function garminActivityIcon(glyph) {\n"
        "  if (!GARMIN_ACTIVITY_PATHS[glyph]) {\n"
        "    throw new Error(`Unknown Garmin activity glyph: ${glyph}`);\n"
        "  }\n"
        "  if (!iconComponents.has(glyph)) {\n"
        "    const Icon = forwardRef(function GarminActivityIcon(\n"
        "      { size = 24, color = \"currentColor\", stroke: _stroke, title, ...props },\n"
        "      ref,\n"
        "    ) {\n"
        "      return createElement(\n"
        "        \"svg\",\n"
        "        {\n"
        "          ref,\n"
        "          width: size,\n"
        "          height: size,\n"
        "          viewBox: GARMIN_ICON_VIEW_BOX,\n"
        "          fill: color,\n"
        "          stroke: \"none\",\n"
        "          xmlns: \"http://www.w3.org/2000/svg\",\n"
        "          \"aria-hidden\": title ? undefined : \"true\",\n"
        "          focusable: \"false\",\n"
        "          ...props,\n"
        "        },\n"
        "        title ? createElement(\"title\", null, title) : null,\n"
        "        createElement(\"path\", {\n"
        "          d: GARMIN_ACTIVITY_PATHS[glyph],\n"
        "          transform: GARMIN_ICON_TRANSFORM,\n"
        "        }),\n"
        "      );\n"
        "    });\n"
        "    Icon.displayName = `GarminActivityIcon(${glyph})`;\n"
        "    iconComponents.set(glyph, Icon);\n"
        "  }\n"
        "  return iconComponents.get(glyph);\n"
        "}\n\n"
        "export function garminActivityIconNode(glyph) {\n"
        "  const path = GARMIN_ACTIVITY_PATHS[glyph];\n"
        "  if (!path) throw new Error(`Unknown Garmin activity glyph: ${glyph}`);\n"
        "  return [[\"path\", { d: path, transform: GARMIN_ICON_TRANSFORM, key: glyph }]];\n"
        "}\n",
        encoding="utf-8",
        newline="\n",
    )


def write_svgs(target_dir: Path, paths: dict[str, str]) -> None:
    target_dir.mkdir(parents=True, exist_ok=True)
    for name, path_data in paths.items():
        svg = (
            '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 320 320" '
            'fill="currentColor" role="img">\n'
            f'  <title>{name}</title>\n'
            f'  <path d="{path_data}" transform="{PATH_TRANSFORM}"/>\n'
            '</svg>\n'
        )
        (target_dir / f"garmin-{name}.svg").write_text(svg, encoding="utf-8", newline="\n")


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("source", type=Path, help="Authorized Garmin SVG icon font")
    parser.add_argument("--root", type=Path, default=Path(__file__).resolve().parents[1])
    args = parser.parse_args()

    paths = extract_paths(args.source)
    write_module(args.root / "src" / "garminActivityIcons.js", paths)
    write_svgs(args.root / "docs" / "activity-icons", paths)
    print(f"Extracted {len(paths)} Garmin activity glyphs")


if __name__ == "__main__":
    main()
