import {
  faBaseballBatBall,
  faBasketball,
  faBicycle,
  faBolt,
  faCarSide,
  faDumbbell,
  faFlagCheckered,
  faFutbol,
  faGolfBallTee,
  faHorse,
  faMedal,
  faMountain,
  faPerson,
  faPersonHiking,
  faPersonRunning,
  faPersonSkating,
  faPersonSkiing,
  faPersonSwimming,
  faPersonWalking,
  faSailboat,
  faSnowflake,
  faTableTennisPaddleBall,
  faVolleyball,
  faWater,
} from "@fortawesome/free-solid-svg-icons";

export const SPORT_META = {
  running: { label: "Running", color: "#d65b3d", icon: faPersonRunning },
  cycling: { label: "Cycling", color: "#3378a5", icon: faBicycle },
  swimming: { label: "Swimming", color: "#168da0", icon: faPersonSwimming },
  walking: { label: "Walking", color: "#8b6f47", icon: faPersonWalking },
  hiking: { label: "Hiking", color: "#4f7b52", icon: faPersonHiking },
  strength: { label: "Strength", color: "#6d5b91", icon: faDumbbell },
  fitness: { label: "Fitness", color: "#bc4d78", icon: faBolt },
  skiing: { label: "Skiing", color: "#607fa1", icon: faPersonSkiing },
  snowboarding: { label: "Snowboarding", color: "#65758b", icon: faSnowflake },
  golf: { label: "Golf", color: "#768f42", icon: faGolfBallTee },
  racket: { label: "Racket sports", color: "#d38a2f", icon: faTableTennisPaddleBall },
  team_sport: { label: "Team sports", color: "#bb623d", icon: faFutbol },
  water_sport: { label: "Water sports", color: "#277f91", icon: faSailboat },
  rowing: { label: "Rowing", color: "#407c85", icon: faWater },
  yoga: { label: "Yoga & mobility", color: "#92678e", icon: faPerson },
  climbing: { label: "Climbing", color: "#735f46", icon: faMountain },
  equestrian: { label: "Equestrian", color: "#8d643e", icon: faHorse },
  motorsport: { label: "Motorsport", color: "#53606b", icon: faFlagCheckered },
  overland: { label: "Overland", color: "#7c6448", icon: faCarSide },
  boating: { label: "Boating", color: "#316f91", icon: faSailboat },
  snorkeling: { label: "Snorkeling", color: "#0e8795", icon: faPersonSwimming },
  multisport: { label: "Multisport", color: "#a8554c", icon: faMedal },
  skating: { label: "Skating", color: "#5b7d99", icon: faPersonSkating },
  baseball: { label: "Baseball", color: "#a65b3c", icon: faBaseballBatBall },
  basketball: { label: "Basketball", color: "#c2742e", icon: faBasketball },
  volleyball: { label: "Volleyball", color: "#597eb7", icon: faVolleyball },
  other: { label: "Other", color: "#66756f", icon: faBolt },
};

export function sportIcon(type) {
  return (SPORT_META[type] ?? SPORT_META.other).icon;
}
